version: '3.8'

services:
  app:
    image: node:alpine
    container_name: vite-node
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "apk update && apk add xdg-utils && npm install && npm run dev --host"
